# Use the official Jenkins LTS image as a base
FROM jenkins/jenkins:lts

# Switch to root user to install Docker CLI
USER root

# Install necessary packages for Docker CLI installation
RUN apt-get update && \
    apt-get install -y apt-transport-https \
    ca-certificates curl gnupg2 \
    software-properties-common

# Add Docker’s official GPG key
RUN curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -

# Add Docker repository
RUN add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"

# Install Docker CLI
RUN apt-get update && \
    apt-get install -y docker-ce-cli

# Switch back to the jenkins user
USER jenkins

